name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Setup .NET
        uses: actions/setup-dotnet@v3  # Updated to the latest version
        with:
          dotnet-version: '8.0.x'  # Set this to your target .NET version

      - name: Restore dependencies
        run: dotnet restore ims-aspnet-ci-cd/IMS.csproj  # Updated path to IMS.csproj

      - name: Build
        run: dotnet build ims-aspnet-ci-cd/IMS.csproj --configuration Release --no-restore  # Updated path to IMS.csproj

      - name: Run Tests
        run: dotnet test ims-aspnet-ci-cd/IMSTests/IMSTests.csproj --no-restore --verbosity normal  # Adjust path if necessary
