name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Set this to your target .NET version

      - name: Restore dependencies
        run: dotnet restore IMS/IMS.csproj

      - name: Build
        run: dotnet build IMS/IMS.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test IMS/IMS.csproj --no-restore --verbosity normal
